dependencies:
  - python=3
  - pip:
    - spacy
    - ipykernel
    - scipy
    - numpy
    - scikit-learn
    - matplotlib
    - pandas
    - thinc
    - geoplotlib
    - Seaborn
    - ggplot
    - Bokeh
    - Plotly
    - pygal
    - missingno
    - Orange3
    - XGBoost
    - NuPIC
    - Milk
    - Caffe
    - Theano
    - TensorFlow
    - Keras
